In [1]:
import pandas as pd
import os

In [2]:
data_path = "../data/raw"

csv_files = [f for f in os.listdir(data_path) if f.endswith(".csv")]

print(csv_files)

['axis_bluechip.csv', 'icici_bluechip.csv', 'kotak_bluechip.csv', 'nippon_large_cap.csv', 'sbi_bluechip.csv']

In [3]:
for file in csv_files:

    print("\n" + "="*60)
    print(f"Dataset: {file}")

    df = pd.read_csv(f"{data_path}/{file}")

    print("\nShape:")
    print(df.shape)

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

============================================================
Dataset: axis_bluechip.csv

Shape:
(3565, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date        nav
0  01-06-2026  6156.7532
1  29-05-2026  6151.1139
2  27-05-2026  6146.6118
3  26-05-2026  6144.0004
4  25-05-2026  6144.8478

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

============================================================
Dataset: icici_bluechip.csv

Shape:
(3307, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  01-06-2026  103.0948
1  31-05-2026  104.3083
2  29-05-2026  104.3129
3  27-05-2026  105.9296
4  26-05-2026  105.5115

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

============================================================
Dataset: kotak_bluechip.csv

Shape:
(3301, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  01-06-2026  246.9814
1  29-05-2026  248.6673
2  27-05-2026  251.2273
3  26-05-2026  251.2702
4  25-05-2026  249.2266

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

============================================================
Dataset: nippon_large_cap.csv

Shape:
(3298, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date      nav
0  01-06-2026  97.1944
1  29-05-2026  98.4656
2  27-05-2026  99.8092
3  26-05-2026  99.4356
4  25-05-2026  99.8047

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

============================================================
Dataset: sbi_bluechip.csv

Shape:
(3236, 2)

Data Types:
date     object
nav     float64
dtype: object

First 5 Rows:

         date       nav
0  01-06-2026  104.7025
1  29-05-2026  104.6570
2  27-05-2026  104.5833
3  26-05-2026  104.5269
4  25-05-2026  104.5215

Missing Values:
date    0
nav     0
dtype: int64

Duplicate Rows:
0

In [4]:
summary = []

for file in csv_files:

    df = pd.read_csv(f"{data_path}/{file}")

    summary.append({
        "Dataset": file,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicates": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)
summary_df

                Dataset  Rows  Columns  Missing Values  Duplicates
0     axis_bluechip.csv  3565        2               0           0
1    icici_bluechip.csv  3307        2               0           0
2    kotak_bluechip.csv  3301        2               0           0
3  nippon_large_cap.csv  3298        2               0           0
4      sbi_bluechip.csv  3236        2               0           0

lOad fund manager file

In [7]:
import pandas as pd

fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

EXPLORE FUND MANAGER

In [8]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [9]:
fund_master['fund_house'].unique()

array(['SBI Mutual Fund', 'HDFC Mutual Fund', 'ICICI Prudential MF',
       'Nippon India MF', 'Kotak Mahindra MF', 'Axis Mutual Fund',
       'Aditya Birla Sun Life MF', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [10]:
fund_master['category'].unique()

array(['Equity', 'Debt'], dtype=object)

In [11]:
fund_master['sub_category'].unique()

array(['Large Cap', 'Small Cap', 'Gilt', 'Mid Cap', 'Short Duration',
       'Value', 'Liquid', 'Index/ETF', 'Flexi Cap', 'Index',
       'Large & Mid Cap', 'ELSS'], dtype=object)

In [15]:
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

AMFI CODE COLOMUNS

In [16]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [17]:
nav_history.columns

Index(['amfi_code', 'date', 'nav'], dtype='object')

Validate code

In [19]:
master_codes = set(fund_master['amfi_code'])

nav_codes = set(nav_history['amfi_code'])

missing_codes = master_codes - nav_codes

print("Missing Codes:", len(missing_codes))

if len(missing_codes) > 0:
    print(missing_codes)
else:
    print("All AMFI codes from fund_master exist in nav_history")

Missing Codes: 0
All AMFI codes from fund_master exist in nav_history

Data Qyality summary
 # Day 1 Data Quality Summary

* Loaded and inspected all provided datasets.
* Verified dataset dimensions, schema, and sample records.
* Explored fund master data and identified 10 unique fund houses.
* Reviewed categories, sub-categories, and risk categories.
* Validated AMFI codes between fund_master and nav_history datasets using Pandas merge operations.
* No missing values or duplicate records were observed in the fetched NAV datasets.
* Data is ready for cleaning and ETL processing in Day 2.